version = 1

test_patterns = [
    "test/**",
    "tests/**",
    "**/test/**",
    "**/tests/**",
]

[[analyzers]]
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"
max_line_length = 79

[[analyzers]]
name = "docker"
